# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginpage.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.setEnabled(True)
        LoginWindow.resize(800, 600)
        LoginWindow.setMinimumSize(QtCore.QSize(800, 600))
        LoginWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(80, 80, 80, 80)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("apple.png"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.le_id = QtWidgets.QLineEdit(self.centralwidget)
        self.le_id.setMinimumSize(QtCore.QSize(0, 50))
        self.le_id.setMaxLength(10)
        self.le_id.setObjectName("le_id")
        self.verticalLayout_2.addWidget(self.le_id)
        self.le_pw = QtWidgets.QLineEdit(self.centralwidget)
        self.le_pw.setMinimumSize(QtCore.QSize(0, 50))
        self.le_pw.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.le_pw.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.le_pw.setMaxLength(10)
        self.le_pw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_pw.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.le_pw.setObjectName("le_pw")
        self.verticalLayout_2.addWidget(self.le_pw)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_login.setObjectName("btn_login")
        self.horizontalLayout.addWidget(self.btn_login)
        self.btn_enjoy = QtWidgets.QPushButton(self.centralwidget)
        self.btn_enjoy.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_enjoy.setObjectName("btn_enjoy")
        self.horizontalLayout.addWidget(self.btn_enjoy)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)
        self.menu_help_1 = QtWidgets.QAction(LoginWindow)
        self.menu_help_1.setStatusTip("")
        self.menu_help_1.setObjectName("menu_help_1")
        self.menu_help_2 = QtWidgets.QAction(LoginWindow)
        self.menu_help_2.setObjectName("menu_help_2")
        self.menu_help.addAction(self.menu_help_1)
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(LoginWindow)
        self.btn_login.clicked.connect(LoginWindow.func_login)
        self.menubar.triggered['QAction*'].connect(LoginWindow.menu)
        self.btn_enjoy.clicked.connect(LoginWindow.func_enjoy)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "LoginWindow"))
        self.label.setText(_translate("LoginWindow", "MOVIE PROGRAM"))
        self.le_id.setPlaceholderText(_translate("LoginWindow", "Please, Enter your ID"))
        self.le_pw.setPlaceholderText(_translate("LoginWindow", "Please, Enter your PW"))
        self.btn_login.setText(_translate("LoginWindow", "LOGIN"))
        self.btn_enjoy.setText(_translate("LoginWindow", "ENJOY"))
        self.menu_help.setTitle(_translate("LoginWindow", "Help"))
        self.menu_help_1.setText(_translate("LoginWindow", "About MOVIE PROGRAM..."))
        self.menu_help_1.setIconText(_translate("LoginWindow", "About MOVIE PROGRAM"))
        self.menu_help_1.setToolTip(_translate("LoginWindow", "About MOVIE PROGRAM"))
        self.menu_help_2.setText(_translate("LoginWindow", "Text Type"))

